# NPM Modules

- name: node | install npm modules
  npm: >
    name={{ item }}
    global=yes
    state=latest
  with_items: node.npm
  when: node.npm is defined

# TODO : run 'npm install' inside the project directories
